// SPDX-License-Identifier: GPL-2.0-only

#ifndef ENCORE_FAS_DET_H
#define ENCORE_FAS_DET_H

#include <linux/compiler.h>
#include <linux/errno.h>
#include <linux/kernel.h>
#include <linux/math64.h>
#include <linux/string.h>
#include <linux/types.h>

#include "uapi/encore_fas_uapi.h"

#define FAS_Q 16
#define FAS_Q_ONE (1LL << FAS_Q)

/* Tolerance of a deficit and half-width of a rate band, in percent. */
#define FAS_TOL_PCT 5
#define FAS_TOL_Q (FAS_Q_ONE * FAS_TOL_PCT / 100)

/* CUSUM alarm limit and single interval limit, in periods. */
#define FAS_CUSUM_LIMIT_Q FAS_Q_ONE
#define FAS_CUSUM_CLIP_Q (FAS_Q_ONE / 2)
#define FAS_RECIP_SHIFT 48

/* Minimum slot loss count for a large hitch. */
#define FAS_MISS_BIG 3

/* Minimum period difference between two frame rates, in percent. */
#define FAS_MIN_RATIO_PCT 112

/*
 * Multiplier for fallback margin in mean absolute deviations.
 * Used before the quantile tracker has sufficient samples.
 */
#ifndef FAS_NOISE_MULT
#define FAS_NOISE_MULT 6
#endif

/*
 * Margin tracks the FAS_QUANT_NUM/FAS_QUANT_DEN quantile of frame lateness
 * using a fixed-step Robbins-Monro update. This holds the false hitch rate
 * stable for any noise distribution.
 */
#define FAS_QUANT_NUM 1999
#define FAS_QUANT_DEN 2000

/* Right shift value to calculate step size from mean absolute deviation. */
#define FAS_QUANT_STEP_SHIFT 2

/*
 * The hitch margin H never exceeds ref * (1 - 2^-FAS_MARGIN_CAP_SHIFT), which
 * is 0.75 * ref by default.
 *
 * The quantile tracker only sees frames below ref + H. Jank that stays below
 * that threshold is learned as noise, which raises the quantile and H until
 * H reaches its old cap, ref. At H = ref a single missed frame slot (interval
 * 2P) sits on the threshold, and jitter decides whether it is reported. With
 * this cap the threshold stays below 1.75 * ref, so a missed slot is always
 * reported. H is still at least V / 2. Use a larger shift for a higher cap.
 */
#ifndef FAS_MARGIN_CAP_SHIFT
#define FAS_MARGIN_CAP_SHIFT 2
#endif

/*
 * Required count of normal frames before using adaptive quantile values.
 * Warmup needs several thousand frames to collect sufficient sample data.
 */
#define FAS_QUANT_WARMUP 4096

#define FAS_WIN_PERIODS 8
#define FAS_OK_WINDOWS 2
#define FAS_UP_WINDOWS 2
#define FAS_DOWN_WINDOWS 4
#define FAS_PAUSE_PERIODS 10

/* Idle poll period in minimum window units (2 seconds). */
#define FAS_IDLE_POLL_WINS 8
#define FAS_NONE 0xffu
#define FAS_OUT_MAX 4

/* Watchdog states. */
#define FAS_WD_ARMED 0
#define FAS_WD_SOFT_SENT 1
#define FAS_WD_HARD_SENT 2
#define FAS_WD_IDLE 3

/**
 * @brief Frame rate target parameters.
 */
struct fas_target {
	/** Target period in ticks. */
	u32 period;
	/** Half-width of tolerance band in ticks. */
	u32 band;
	/** Frame rate in frames per second. */
	u32 fps;
};

/**
 * @brief Configuration settings for detector.
 */
struct fas_cfg {
	/** Active target period in ticks. */
	u64 period;
	/** Value 2^48 divided by active period. */
	u64 recip;
	/** Display vsync period in ticks. */
	u64 vsync;
	/** Frame interval threshold for pause state. */
	u64 pause;
	/** Minimum window length (250 ms). */
	u64 win_min;
	/** Required window length for active target. */
	u64 win_need;
	/** Index of active target. */
	u8 active;
	/** Total count of configured targets. */
	u8 count;
	/** Percentage of stalls that are held out of boosting (0 to 100). */
	u8 holdout_pct;
	/** Flag to prevent switching to lower frame rates. */
	u8 lock_down;
	u8 pad[4];
	/** Configured targets ordered from fastest to slowest rate. */
	struct fas_target tgt[FAS_MAX_TARGETS];
};

/**
 * @brief Detector state updated per frame.
 */
struct fas_hot {
	/** Timestamp of last frame. */
	u64 last;
	/** Start timestamp of current window. */
	u64 win_start;
	/** Moving average frame period, multiplied by 16. */
	u64 cadence_q4;
	/** Moving mean absolute deviation, multiplied by 16. */
	u64 dev_q4;
	/** Tracked quantile of frame deviation in Q16 ticks. */
	u64 quant_q;
	/** Accumulated CUSUM deficit in Q16 format. */
	s64 cusum_q;
	/** Frame count in current window. */
	u32 win_n;
	/** Count of normal updates, capped at FAS_QUANT_WARMUP. */
	u16 quant_n;
	/** Set to 1 when first frame is recorded. */
	u8 have_last;
	/** Set to 1 while initial target rate is selected. */
	u8 acquiring;
	/** Set to 1 when performance is below active target. */
	u8 degraded;
	/** Set to 1 when watchdog detects pause state. */
	u8 paused;
	/** Current watchdog state (FAS_WD_*). */
	u8 wd_stage;
	/** Count of consecutive normal windows. */
	u8 ok_windows;
	/** Candidate target index matching recent windows, or FAS_NONE. */
	u8 pending;
	/** Consecutive window count matching pending target. */
	u8 pending_windows;
	/** Set to 1 while the current stall is in the holdout group. */
	u8 holdout;
	/** Sequence number of last event. */
	u32 seq;
};

/**
 * @brief Single event generated by detector.
 */
struct fas_ev {
	/** Event type (enum fas_event_type). */
	u32 type;
	/** Event flags (FAS_EVF_*). */
	u32 flags;
	/** Count of missed frame slots. */
	u32 missed;
	/** Active frame rate target. */
	u32 fps;
	/** Measured interval or elapsed time in ticks. */
	u64 ticks;
};

/**
 * @brief Event output container from detector call.
 */
struct fas_out {
	/** Event count in ev array. */
	u32 n;
	/** Set to true if process check is required. */
	bool idle;
	/** Array of generated events. */
	struct fas_ev ev[FAS_OUT_MAX];
};

static __always_inline u64 fas_abs_diff(u64 a, u64 b)
{
	return a > b ? a - b : b - a;
}

/**
 * @brief Calculates reference interval.
 *
 * @param c Configuration settings.
 * @param h Detector state.
 * @return Reference interval in ticks.
 */
static __always_inline u64 fas_ref(const struct fas_cfg *c,
				   const struct fas_hot *h)
{
	u64 p = c->period;

	return min_t(u64, max_t(u64, p, h->cadence_q4 >> 4), p << 1);
}

/**
 * @brief Calculates hitch threshold margin.
 *
 * Uses tracked deviation quantile if sufficient samples exist.
 * Falls back to fixed multiple of mean absolute deviation during warmup.
 * The result is at least V / 2 and at most 0.75 * ref (see FAS_MARGIN_CAP_SHIFT).
 *
 * @param c Configuration settings.
 * @param h Detector state.
 * @param ref Reference interval in ticks.
 * @return Margin value in ticks.
 */
static __always_inline u64 fas_margin(const struct fas_cfg *c,
				      const struct fas_hot *h, u64 ref)
{
	u64 adaptive = h->quant_n >= FAS_QUANT_WARMUP ?
			       h->quant_q >> FAS_Q :
			       (h->dev_q4 * FAS_NOISE_MULT) >> 4;
	u64 cap = max_t(u64, c->vsync >> 1, ref - (ref >> FAS_MARGIN_CAP_SHIFT));

	adaptive = max_t(u64, c->vsync >> 1, adaptive);
	return min_t(u64, min_t(u64, adaptive, cap), ref);
}

/**
 * @brief Calculates delay to soft watchdog timer expiration.
 *
 * @param c Configuration settings.
 * @param h Detector state.
 * @return Delay value in ticks.
 */
static __always_inline u64 fas_soft_ticks(const struct fas_cfg *c,
					  const struct fas_hot *h)
{
	u64 ref = fas_ref(c, h);

	return ref + fas_margin(c, h, ref);
}

/**
 * @brief Calculates delay to hard watchdog timer expiration.
 *
 * @param c Configuration settings.
 * @param h Detector state.
 * @return Delay value in ticks.
 */
static __always_inline u64 fas_hard_ticks(const struct fas_cfg *c,
					  const struct fas_hot *h)
{
	u64 ref = fas_ref(c, h);

	return ref * FAS_MISS_BIG + fas_margin(c, h, ref);
}

/**
 * @brief Draws the holdout group of a stall.
 *
 * The draw hashes the timestamp of the last frame, which is fixed before the
 * stall starts. It cannot depend on the length of the stall. Fibonacci hashing
 * spreads the low tick bits over the high bits, and the multiply-shift maps
 * them to 0..99 without a division.
 *
 * @param c Configuration settings.
 * @param h Detector state.
 * @return true if the stall is held out of boosting.
 */
static __always_inline bool fas_holdout_draw(const struct fas_cfg *c,
					     const struct fas_hot *h)
{
	u32 x = (u32)((h->last * 0x9E3779B97F4A7C15ULL) >> 32);

	return c->holdout_pct && (((u64)x * 100) >> 32) < c->holdout_pct;
}

/**
 * @brief Adds an event to output buffer.
 *
 * @param c Configuration settings.
 * @param out Output container.
 * @param type Event type ID.
 * @param flags Event flags.
 * @param missed Count of missed frame slots.
 * @param ticks Interval or timestamp in ticks.
 */
static inline void fas_emit(const struct fas_cfg *c, struct fas_out *out,
			    u32 type, u32 flags, u32 missed, u64 ticks)
{
	struct fas_ev *ev;

	if (unlikely(out->n >= FAS_OUT_MAX))
		return;

	ev = &out->ev[out->n++];
	ev->type = type;
	ev->flags = flags;
	ev->missed = missed;
	ev->fps = c->tgt[c->active].fps;
	ev->ticks = ticks;
}

/**
 * @brief Sets active target rate and updates timing parameters.
 *
 * @param c Configuration settings.
 * @param idx Index of target rate.
 */
static inline void fas_det_set_active(struct fas_cfg *c, u32 idx)
{
	c->active = idx;
	c->period = c->tgt[idx].period;
	c->recip = div64_u64(1ULL << FAS_RECIP_SHIFT, c->period);
	c->win_need = max_t(u64, c->win_min, c->period * FAS_WIN_PERIODS);
}

/**
 * @brief Validates frame rates and initializes detector state.
 *
 * Modifies parameters only if inputs are valid.
 *
 * @param c Output configuration structure.
 * @param h Output detector state structure.
 * @param freq Timer counter frequency in Hz.
 * @param fps Array of frame rate targets.
 * @param count Number of frame rate targets (1 to FAS_MAX_TARGETS).
 * @param vsync Display vsync period in ticks, or 0 for fastest target period.
 * @param lock_down Set to true to disable switching to lower frame rates.
 * @return 0 on success, or -EINVAL if arguments are invalid.
 */
static int fas_det_setup(struct fas_cfg *c, struct fas_hot *h, u64 freq,
			 const u32 *fps, u32 count, u64 vsync, bool lock_down)
{
	struct fas_cfg tmp;
	u32 sorted[FAS_MAX_TARGETS];
	u32 i, j;

	if (!count || count > FAS_MAX_TARGETS)
		return -EINVAL;

	for (i = 0; i < count; i++) {
		u32 key = fps[i];

		if (key == 0 || key > 1000)
			return -EINVAL;
		for (j = i; j > 0 && sorted[j - 1] < key; j--)
			sorted[j] = sorted[j - 1];
		sorted[j] = key;
	}

	memset(&tmp, 0, sizeof(tmp));
	for (i = 0; i < count; i++) {
		struct fas_target *t = &tmp.tgt[i];

		t->fps = sorted[i];
		t->period = (u32)div_u64(freq + (sorted[i] >> 1), sorted[i]);
		t->band = t->period * FAS_TOL_PCT / 100;
		if (i && (u64)t->period * 100 <
				 (u64)tmp.tgt[i - 1].period * FAS_MIN_RATIO_PCT)
			return -EINVAL;
	}

	if (vsync && (vsync < freq / 1000 || vsync > freq / 10))
		return -EINVAL;

	tmp.count = count;
	tmp.lock_down = lock_down;
	tmp.vsync = vsync ? vsync : tmp.tgt[0].period;
	tmp.win_min = freq / 4;
	tmp.pause = max_t(u64, freq,
			  (u64)tmp.tgt[count - 1].period * FAS_PAUSE_PERIODS);
	fas_det_set_active(&tmp, 0);

	*c = tmp;
	memset(h, 0, sizeof(*h));
	h->acquiring = 1;
	h->pending = FAS_NONE;
	h->wd_stage = FAS_WD_IDLE;
	return 0;
}

static __always_inline int fas_band_index(const struct fas_cfg *c, u64 mean)
{
	u32 i;

	for (i = 0; i < c->count; i++)
		if (fas_abs_diff(mean, c->tgt[i].period) <= c->tgt[i].band)
			return (int)i;
	return -1;
}

/**
 * @brief Switches active target rate and resets deficit metrics.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param idx Index of new target rate.
 * @param out Output container.
 */
static noinline void fas_det_switch(struct fas_hot *h, struct fas_cfg *c,
				    u32 idx, struct fas_out *out)
{
	fas_det_set_active(c, idx);
	h->cadence_q4 = c->period << 4;
	h->pending = FAS_NONE;
	h->pending_windows = 0;
	h->degraded = 0;
	h->ok_windows = 0;
	h->cusum_q = 0;
	fas_emit(c, out, FAS_EVENT_RATE_SWITCH, 0, 0, 0);
}

/**
 * @brief Selects initial target rate during acquisition window.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param span Acquisition window duration in ticks.
 * @param out Output container.
 */
static noinline void fas_det_acquire(struct fas_hot *h, struct fas_cfg *c,
				     u64 span, struct fas_out *out)
{
	u64 mean = div_u64(span, h->win_n);
	int k = fas_band_index(c, mean);
	u32 i;

	if (k < 0) {
		k = 0;
		for (i = 0; i < c->count; i++)
			if (c->tgt[i].period <= mean)
				k = (int)i;
	}

	h->acquiring = 0;
	h->wd_stage = FAS_WD_ARMED;
	fas_det_switch(h, c, (u32)k, out);
	h->win_start = h->last;
	h->win_n = 0;
}

/**
 * @brief Evaluates window frame rate against candidate target.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param mean Mean frame interval in ticks.
 * @param out Output container.
 */
static noinline void fas_det_rate_track(struct fas_hot *h, struct fas_cfg *c,
					u64 mean, struct fas_out *out)
{
	int k = fas_band_index(c, mean);
	bool slower;
	u32 need;

	if (k < 0 || (u32)k == c->active) {
		h->pending = FAS_NONE;
		h->pending_windows = 0;
		return;
	}

	if ((u32)k != h->pending) {
		h->pending = (u8)k;
		h->pending_windows = 0;
	}
	if (h->pending_windows < 255)
		h->pending_windows++;

	slower = c->tgt[k].period > c->period;
	if (slower && c->lock_down)
		return;

	need = slower ? FAS_DOWN_WINDOWS : FAS_UP_WINDOWS;
	if (h->pending_windows >= need)
		fas_det_switch(h, c, (u32)k, out);
}

/**
 * @brief Process evaluation at end of measurement window.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param now Current timestamp in ticks.
 * @param out Output container.
 */
static noinline void fas_det_window_close(struct fas_hot *h, struct fas_cfg *c,
					  u64 now, struct fas_out *out)
{
	u64 span = now - h->win_start;
	u64 mean = div_u64(span, h->win_n);

	if (h->degraded) {
		u64 rho_q = div64_u64(span << FAS_Q, (u64)h->win_n * c->period);

		if (rho_q <= (u64)(FAS_Q_ONE + FAS_TOL_Q)) {
			if (++h->ok_windows >= FAS_OK_WINDOWS) {
				h->degraded = 0;
				h->ok_windows = 0;
				h->cusum_q = 0;
				fas_emit(c, out, FAS_EVENT_RECOVERED, 0, 0, mean);
			}
		} else {
			h->ok_windows = 0;
		}
	}

	fas_det_rate_track(h, c, mean, out);
	h->win_start = now;
	h->win_n = 0;
}

/**
 * @brief Reports frame hitch event.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param delta Measured frame interval in ticks.
 * @param ref Reference interval in ticks.
 * @param margin Hitch margin threshold in ticks.
 * @param flags Event flags.
 * @param out Output container.
 */
static noinline void fas_det_hitch(const struct fas_hot *h,
				   const struct fas_cfg *c, u64 delta, u64 ref,
				   u64 margin, u32 flags, struct fas_out *out)
{
	u64 missed = div64_u64(delta - margin, ref);
	u32 type = missed >= FAS_MISS_BIG ? FAS_EVENT_BIG_JANK :
					    FAS_EVENT_SMALL_JANK;

	if (h->degraded && type != FAS_EVENT_BIG_JANK)
		return;

	fas_emit(c, out, type, flags, (u32)min_t(u64, missed, 0xffff), delta);
}

/**
 * @brief Resets detector state after pause or frame gap.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param now Current timestamp in ticks.
 * @param out Output container.
 */
static noinline void fas_det_resync(struct fas_hot *h, const struct fas_cfg *c,
				    u64 now, struct fas_out *out)
{
	if (h->paused)
		fas_emit(c, out, FAS_EVENT_RESUMED, 0, 0, 0);

	h->paused = 0;
	h->holdout = 0;
	h->degraded = 0;
	h->ok_windows = 0;
	h->cusum_q = 0;
	h->pending = FAS_NONE;
	h->pending_windows = 0;
	h->win_start = now;
	h->win_n = 0;
	if (!h->acquiring) {
		h->wd_stage = FAS_WD_ARMED;
		h->cadence_q4 = c->period << 4;
	}
}

/*
 * Updates cadence, deviation, and lateness quantile.
 *
 * Quantile tracks frame lateness relative to cadence using a Robbins-Monro
 * update rule. Step size adjusts based on deviation to maintain reliable
 * hitch detection across different frame rates.
 */
static __always_inline void fas_det_noise_update(struct fas_hot *h,
						 const struct fas_cfg *c,
						 u64 delta)
{
	u64 cadence = h->cadence_q4 >> 4;
	u64 a = h->dev_q4 >> 4;
	u64 dev = min_t(u64, fas_abs_diff(delta, cadence), c->vsync);
	u64 late_q = (delta > cadence ? delta - cadence : 0) << FAS_Q;
	u64 step_q = max_t(u64, 1, (a << FAS_Q) >> FAS_QUANT_STEP_SHIFT);

	h->dev_q4 = (u64)((s64)h->dev_q4 +
			  ((((s64)dev << 4) - (s64)h->dev_q4) >> 4));
	h->cadence_q4 = (u64)((s64)h->cadence_q4 +
			      ((((s64)delta << 4) - (s64)h->cadence_q4) >> 3));

	if (late_q > h->quant_q) {
		h->quant_q += div_u64(step_q * FAS_QUANT_NUM, FAS_QUANT_DEN);
	} else {
		u64 down = div_u64(step_q * (FAS_QUANT_DEN - FAS_QUANT_NUM),
				   FAS_QUANT_DEN);

		h->quant_q -= min_t(u64, h->quant_q, down);
	}
	if (h->quant_n < FAS_QUANT_WARMUP)
		h->quant_n++;
}

/**
 * @brief Adds frame interval to CUSUM deficit tracking.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param delta Measured frame interval in ticks.
 * @return true if CUSUM exceeds alarm limit, false otherwise.
 */
static __always_inline bool fas_det_cusum(struct fas_hot *h,
					  const struct fas_cfg *c, u64 delta)
{
	u64 p = c->period;
	s64 x = ((s64)min_t(u64, delta, p + (p >> 1)) - (s64)p) *
			(s64)c->recip >> (FAS_RECIP_SHIFT - FAS_Q);
	s64 s = h->cusum_q + x - FAS_TOL_Q;

	h->cusum_q = s > 0 ? s : 0;
	return unlikely(h->cusum_q >= FAS_CUSUM_LIMIT_Q);
}

/**
 * @brief Processes a single frame event.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param now Frame timestamp in ticks.
 * @param out Output container for generated events.
 * @return Watchdog timer delay in ticks, or 0 if timer state is unchanged.
 */
static u64 fas_det_frame(struct fas_hot *h, struct fas_cfg *c, u64 now,
			 struct fas_out *out)
{
	u64 delta, ref, margin;
	u32 flags;

	out->n = 0;
	out->idle = false;

	if (unlikely(!h->have_last)) {
		h->have_last = 1;
		h->acquiring = 1;
		h->last = now;
		h->win_start = now;
		h->win_n = 0;
		return 0;
	}

	/* Ignore frames arriving out of order across CPUs. */
	delta = now - h->last;
	if (unlikely((s64)delta <= 0))
		return 0;
	h->last = now;

	if (unlikely(h->paused || delta >= c->pause)) {
		fas_det_resync(h, c, now, out);
		return h->acquiring ? 0 : fas_soft_ticks(c, h);
	}

	if (unlikely(h->acquiring)) {
		h->win_n++;
		if (now - h->win_start < c->win_min)
			return 0;
		fas_det_acquire(h, c, now - h->win_start, out);
		return fas_soft_ticks(c, h);
	}

	flags = h->wd_stage ? FAS_EVF_WATCHDOG : 0;
	if (unlikely(h->holdout))
		flags |= FAS_EVF_HOLDOUT;
	h->holdout = 0;
	h->wd_stage = FAS_WD_ARMED;

	ref = fas_ref(c, h);
	margin = fas_margin(c, h, ref);
	if (unlikely(delta >= ref + margin))
		fas_det_hitch(h, c, delta, ref, margin, flags, out);
	else
		fas_det_noise_update(h, c, delta);

	if (likely(!h->degraded) && fas_det_cusum(h, c, delta)) {
		fas_emit(c, out, FAS_EVENT_DEGRADED, 0, 0, delta);
		h->degraded = 1;
		h->cusum_q = 0;
	}

	h->win_n++;
	if (unlikely(now - h->win_start >= c->win_need))
		fas_det_window_close(h, c, now, out);

	return fas_soft_ticks(c, h);
}

/**
 * @brief Processes watchdog timer callback.
 *
 * @param h Detector state.
 * @param c Configuration settings.
 * @param now Current timestamp in ticks.
 * @param out Output container for generated events.
 * @return Delay to next watchdog state in ticks.
 */
static u64 fas_det_wd_fire(struct fas_hot *h, const struct fas_cfg *c, u64 now,
			   struct fas_out *out)
{
	u64 elapsed = (s64)(now - h->last) > 0 ? now - h->last : 0;
	u64 limit;

	out->n = 0;
	out->idle = false;

	switch (h->wd_stage) {
	case FAS_WD_ARMED:
    	limit = fas_soft_ticks(c, h);
    	if (elapsed < limit)
        	return 0;
    	h->wd_stage = FAS_WD_SOFT_SENT;
		h->holdout = fas_holdout_draw(c, h);
		fas_emit(c, out, FAS_EVENT_BOOST_SOFT,
			 h->holdout ? FAS_EVF_HOLDOUT : 0, 0, elapsed);
    	limit = fas_hard_ticks(c, h);
    	return limit > elapsed ? limit - elapsed : 1;
	case FAS_WD_SOFT_SENT:
		limit = fas_hard_ticks(c, h);
		if (elapsed < limit)
			return limit - elapsed;
		h->wd_stage = FAS_WD_HARD_SENT;
		fas_emit(c, out, FAS_EVENT_BOOST_HARD,
			 h->holdout ? FAS_EVF_HOLDOUT : 0, 0, elapsed);
		return c->pause > elapsed ? c->pause - elapsed : 1;
	case FAS_WD_HARD_SENT:
		if (elapsed < c->pause)
			return c->pause - elapsed;
		h->wd_stage = FAS_WD_IDLE;
		h->paused = 1;
		fas_emit(c, out, FAS_EVENT_PAUSED, 0, 0, elapsed);
		break;
	default:
		break;
	}

	out->idle = true;
	return c->win_min * FAS_IDLE_POLL_WINS;
}

/**
 * @brief Gets normalized deficit pressure metric.
 *
 * @param h Detector state.
 * @return CUSUM value scaled to Q16 format (maximum 65536).
 */
static __always_inline u32 fas_det_pressure(const struct fas_hot *h)
{
	return (u32)min_t(s64, h->cusum_q, FAS_Q_ONE);
}

#endif
