name: test-composite
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: naidrahiqa/kernel-ci-kit@main
        with:
          defconfig: selene_defconfig
          device_name: selene
          toolchain: greenforce-clang
          extra_make_args: "LLVM=1 LLVM_IAS=1"
